### ISSUE TITLE
Running the circom command without parameters gives an error

### ISSUE THREAD

**Issue by weijiekoh** [iden3/circom#10]
```
$ circom 
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1088:7)
    at Object.<anonymous> (/usr/lib/node_modules/circom/cli.js:44:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

**Comment by jbaylina** [comment]
Fixed in v0.0.14

Thank you for the contribution!
