### ISSUE TITLE
Error calculating witness for Groth16 in v2.2.0

### ISSUE THREAD

**Issue by geovgy** [iden3/circom#308]
There is an issue in the circom runtime that is causing the witness builder to fail. I attempted it with both WASM and C++ compiled circuits, neither having any luck. Regardless if I'm using `circom_tester`, `snarkjs.groth16.fullProve` or `snarkjs.groth16.prove` (attempted with both `snarkjs` versions 0.7.4 and 0.7.1), the error location remains the same.

Here is the error log when testing it:
```
LinkError: WebAssembly.instantiate(): Import #4 module="runtime" function="printDebug": function import requires a callable
      at Object.builder [as WitnessCalculatorBuilder] (node_modules/circom_runtime/build/main.cjs:112:40)
      at wtnsCalculate (node_modules/snarkjs/build/main.cjs:1257:16)
      at Object.groth16FullProve [as fullProve] (node_modules/snarkjs/build/main.cjs:1301:5)
      at prove (utils/prover.ts:207:36)
```

Note, this only occurs on v2.2.0. When I changed the compiler to v2.1.9, I no longer received this issue.

**Comment by numtel** [comment]
I'm guessing there's going to be a new snarkjs version soon once [this pr](https://github.com/iden3/circom_runtime/pull/117) is merged. It fixes this bug.

To use this version right now, put this in your `package.json` file:

```json
  "overrides": {
    "circom_runtime": "iden3/circom_runtime#fix/addMissingPrintDebug"
  },
```
