### ISSUE TITLE
Template with no inputs does looses outputs

### ISSUE THREAD

**Issue by 3sGgpQ8H** [iden3/circom#45]
I have the following circuit:

    template Foo () {
      signal output x;
      x <== 13;
    }
    template Bar () {
      component foo = Foo ();
      foo.x === 13;
    }
    component main = Bar ();

It compiles successfully, but what I run `snarkjs calculatewitness` it reports the following error:

    Error: Signal not initialized: main.foo.x
        at RTCtx.getSignalFullName (/usr/local/lib/node_modules/snarkjs/src/calculateWitness.js:220:19)
        at RTCtx.getPin (/usr/local/lib/node_modules/snarkjs/src/calculateWitness.js:214:21)
        at Object.__f [as Bar] (eval at Circuit (/usr/local/lib/node_modules/snarkjs/src/circuit.js:46:33), <anonymous>:2:20)
        at RTCtx.triggerComponent (/usr/local/lib/node_modules/snarkjs/src/calculateWitness.js:126:41)
        at calculateWitness (/usr/local/lib/node_modules/snarkjs/src/calculateWitness.js:43:45)
        at Circuit.calculateWitness (/usr/local/lib/node_modules/snarkjs/src/circuit.js:59:16)
        at Object.<anonymous> (/usr/local/lib/node_modules/snarkjs/cli.js:308:29)
        at Module._compile (internal/modules/cjs/loader.js:701:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
        at Module.load (internal/modules/cjs/loader.js:600:32)
    ERROR: Error: Signal not initialized: main.foo.x

I played with this code a bit and it seems that in case template has no inputs, something bad happens with its outputs.

    > circom --version
    0.0.31
    > snarkjs --version
    0.1.18
    > uname -a
    Darwin MacBookPro 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64

**Comment by adamalexandru4** [comment]
I also have the same type of error. Any solution?
