### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by 5chdn** [iden3/circom#7]
Testing http://iden3.io/blog/circom-and-snarkjs-tutorial.html

With:

```
template Multiplier() {
	signal private input a;
	signal private input b;
	signal output c;

	c <== a*b;
}

component main = Multiplier();
```

I get:

```
❯ circom circuit.circom -o circuit.json

/usr/lib/node_modules/circom/src/compiler.js:36
async function compile(srcFile) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/circom/cli.js:27:18)
```

My envorinment:

```
❯ sudo npm install -g circom snarkjs                   
/usr/bin/circom -> /usr/lib/node_modules/circom/cli.js
/usr/bin/snarkjs -> /usr/lib/node_modules/snarkjs/cli.js
+ circom@0.0.12
+ snarkjs@0.1.4
updated 2 packages in 7.209s

❯ uname -a
Linux eros 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

❯ nodejs --version
v10.12.0

❯ npm --version
6.4.1
```

Thanks for the session though :)

**Comment by jbaylina** [comment]
@5chdn  Thank you for contributing and for your feedback!.

I'm not able to reproduce this error.  This error generally happen if you run an old version <7.6 ....

https://stackoverflow.com/questions/37815790/syntaxerror-unexpected-token-function-async-await-nodejs

I see that that you are installing npm with sudo. Is it possible that there are 2 nodes installed?

**Comment by 5chdn** [comment]
> Is it possible that there are 2 nodes installed?

Yes, that's the reason, my environment is messed with competing versions. Thanks
