### ISSUE TITLE
Tutorial documentation is broken as of 0.5.38

### ISSUE THREAD

**Issue by jmcph4** [iden3/circom#76]
# Description #
The instructions in both the [tutorial](https://github.com/iden3/circom/blob/744d3b241cd482d668f5c980e9c9160d9db17681/TUTORIAL.md) and [README](https://github.com/iden3/circom/blob/744d3b241cd482d668f5c980e9c9160d9db17681/README.md) are wrong as of circom 0.5.38.

# Steps to Reproduce #

```sh
$ mkdir myproj
$ cd myproj
$ yarn add circom
$ yarn add snarkjs
$ mkdir factor
$ cd factor
$ vim circuit.circom # fill in the file...
$ yarn run circom
yarn run v1.22.5
warning package.json: No license field
$ /home/someuser/dev/misc/node_modules/.bin/circom
Error: ENOENT: no such file or directory, open '/home/someuser/dev/misc/circuit.circom'
    at Object.openSync (fs.js:466:3)
    at Object.readFileSync (fs.js:369:35)
    at constructionPhase (/home/someuser/dev/misc/node_modules/circom/src/construction_phase.js:78:20)
    at compile (/home/someuser/dev/misc/node_modules/circom/src/compiler.js:70:5)
    at run (/home/someuser/dev/misc/node_modules/circom/cli.js:120:11)
    at Object.<anonymous> (/home/someuser/dev/misc/node_modules/circom/cli.js:145:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
ENOENT: no such file or directory, open '/home/someuser/dev/misc/circuit.circom'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ cd ..
$ yarn run circom factor/circuit.circom
yarn run v1.22.5
warning package.json: No license field
$ /home/someuser/dev/misc/node_modules/.bin/circom factor/circuit.circom
Done in 0.23s.
```

Additionally, the command-line flags used in the tutorial aren't even documented in the usage information:

```sh
$ yarn run circom --help
yarn run v1.22.5
warning package.json: No license field
$ /home/someuser/dev/misc/node_modules/.bin/circom --help
circom [input source circuit file] -r [output r1cs file] -c [output c file] -w
[output wasm file] -t [output wat file] -s [output sym file]

Options:
  --version      Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]
  --verbose, -v  Run with verbose logging                              [boolean]
  --fast, -f     Do not optimize constraints                           [boolean]

Copyright (C) 2018  0kims association
    This program comes with ABSOLUTELY NO WARRANTY;
    This is free software, and you are welcome to redistribute it
    under certain conditions; see the COPYING file in the official
    repo directory at  https://github.com/iden3/circom
Done in 0.23s.
```

# Expected Behaviour #
For the tutorial documentation to be correct and to work on the latest stable release.

**Comment by jmcph4** [comment]
See also: #75

**Comment by tippi-fifestarr** [comment]
I also am having this problem

**Comment by tippi-fifestarr** [comment]
Actually my problem is Using Node 14.15.0 npm install -g snarkjs@latest installs "correctly" but no node_modules or package.json are created

**Comment by jmcph4** [comment]
> Actually my problem is Using Node 14.15.0 npm install -g snarkjs@latest installs "correctly" but no node_modules or package.json are created

Are you sure you want a global installation?
